parent=keycloak
import=common/keycloak

styles=css/login.css

# Supported locales
locales=en,es,fr,pt

scripts=

##Logos
kcLogo-MFAErrorIcon=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/CMS/MFA/mfa-error-icon.png
kcLogo-BackButton=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/CMS/MFA/mfa-go-back-icon.png

kcLogoIdP-Lifemiles=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/WebSite/Authentication/LM.svg
kcLogoIdP-facebook=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/WebSite/AVLogin/facebook-logo.png
kcLogoIdP-google=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/WebSite/Authentication/Gmail.svg
kcLogoIdP-linkedin=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/WebSite/AVLogin/linkedin-logo.png
kcLogoIdP-instagram=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/WebSite/AVLogin/instagram-logo.png
kcLogoIdP-twitter=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/WebSite/AVLogin/twitter-logo.png
kcLogoIdP-apple=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/WebSite/Authentication/Apple.svg
kcLogoIdP-microsoft=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/WebSite/Authentication/Apple.svg

kcLogo-GoogleAuthenticator=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/CMS/MFA/mfa-google-auth-icon.png
kcLogo-MicrosoftAuthenticator=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/CMS/MFA/mfa-microsoft-auth-icon.png
kcLogo-SMS=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/CMS/MFA/mfa-sms-icon.png
kcLogo-Email=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/CMS/MFA/mfa-email-icon.svg

kcLogoAuthApp-google-es=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/CMS/MFA/mfa-google-btn-esp.png
kcLogoAuthApp-apple-es=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/CMS/MFA/mfa-apple-btn-esp.png

kcLogoAuthApp-google-en=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/CMS/MFA/mfa-google-btn-eng.png
kcLogoAuthApp-apple-en=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/CMS/MFA/mfa-apple-btn-eng.png

kcLogoSMS-Icon=https://d296xu67oj0g2g.cloudfront.net/lm_cms/images/CMS/MFA/mfa-sms-icon.png

kcAppID-GoogleAuthenticator=google
kcAppID-MicrosoftAuthenticator=microsoft

cacheTemplates=false
cacheThemes=false